commt

diff --git a/.github/workflows/update-data.yml b/.github/workflows/update-data.yml
--- a/.github/workflows/update-data.yml
+++ b/.github/workflows/update-data.yml
@@ -28,15 +28,25 @@ jobs:
         pip install requests
     
     - name: Update data
-      run: python readsheet.py
-    
-    - name: Commit and push if changed
       run: |
-        git config --global user.email "action@github.com"
-        git config --global user.name "GitHub Action"
-        git add public/poster_data.json
-        git commit -m "Update data" || exit 0
-        git push
+        python readsheet.py
+        if [ $? -ne 0 ]; then
+          echo "Error occurred while running readsheet.py"
+          exit 1
+        fi
+    
+    - name: Check if poster_data.json was updated
+      run: |
+        if git diff --exit-code public/poster_data.json; then
+          echo "No changes in poster_data.json"
+        else
+          echo "poster_data.json was updated"
+          git config --global user.email "action@github.com"
+          git config --global user.name "GitHub Action"
+          git add public/poster_data.json
+          git commit -m "Update data"
+          git push
+        fi
 
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
